name: tugasmobile5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/floppy.png
    - assets/iphone.png
    - assets/laptop.png
    - assets/pendrive.png
    - assets/pixel.png
    - assets/tablet.png